#!/usr/bin/env bash
# Conventional Commit message linter.
# Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
# Format:  "type: description"  or  "type!: description" (breaking change)
# Scopes are not used in this project.

set -euo pipefail

commit_msg_file="${1:?usage: commit-msg-lint.sh <commit-msg-file>}"
msg="$(head -1 "$commit_msg_file")"

# Allow merge commits and reverts generated by git itself.
if [[ "$msg" =~ ^Merge\  ]] || [[ "$msg" =~ ^Revert\ \" ]]; then
  exit 0
fi

types="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
pattern="^($types)!?: .+$"

if ! [[ "$msg" =~ $pattern ]]; then
  echo >&2 "ERROR: commit message does not follow Conventional Commits format."
  echo >&2 ""
  echo >&2 "  Expected:  <type>: <description>"
  echo >&2 "  Received:  $msg"
  echo >&2 ""
  echo >&2 "  Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
  echo >&2 "  Example:   feat: add retry logic to executor"
  exit 1
fi
